# Generated by Django 5.2 on 2025-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_consent',
            field=models.BooleanField(default=False),
        ),
    ]
