# Generated by Django 5.2 on 2025-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(blank=True, choices=[('Medium', 'Medium'), ('Large', 'Large'), ('Small', 'Small')], max_length=7, null=True),
        ),
    ]
