# Generated by Django 5.2 on 2025-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_content_post_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
