# Generated by Django 5.2 on 2025-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bread_type',
            field=models.CharField(choices=[('white', 'White Bread'), ('brown', 'Brown Bread')], default='white', max_length=10),
        ),
    ]
