# Generated by Django 5.2 on 2025-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_bread_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bread_type',
        ),
        migrations.AddField(
            model_name='post',
            name='bread',
            field=models.CharField(choices=[('white', 'White Bread'), ('brown', 'Brown Bread')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='meat',
            field=models.CharField(choices=[('turkey', 'Turkey'), ('chicken', 'Grilled Chicken'), ('ham', 'Ham'), ('roast_beef', 'Roast Beef'), ('tuna', 'Tuna'), ('salami', 'Salami'), ('no_meat', 'No Meat')], default='chicken', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='10-15', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('6', '6-inch'), ('12', 'Footlong')], default='6', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='temp',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='vegan',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='False', max_length=20),
        ),
    ]
