# Generated by Django 5.2 on 2025-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_sauce_alter_post_price_alter_post_vegan_post_sauces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sauces',
        ),
        migrations.AddField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('mayo', 'Mayonnaise'), ('mustard', 'Mustard'), ('ketchup', 'Ketchup'), ('bbq', 'BBQ Sauce'), ('ranch', 'Ranch'), ('sweet_onion', 'Sweet Onion'), ('chipotle', 'Chipotle Southwest'), ('honey_mustard', 'Honey Mustard'), ('hot_sauce', 'Hot Sauce'), ('none', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('mayo', 'Mayonnaise'), ('mustard', 'Mustard'), ('ketchup', 'Ketchup'), ('bbq', 'BBQ Sauce'), ('ranch', 'Ranch'), ('sweet_onion', 'Sweet Onion'), ('chipotle', 'Chipotle Southwest'), ('honey_mustard', 'Honey Mustard'), ('hot_sauce', 'Hot Sauce'), ('none', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('mayo', 'Mayonnaise'), ('mustard', 'Mustard'), ('ketchup', 'Ketchup'), ('bbq', 'BBQ Sauce'), ('ranch', 'Ranch'), ('sweet_onion', 'Sweet Onion'), ('chipotle', 'Chipotle Southwest'), ('honey_mustard', 'Honey Mustard'), ('hot_sauce', 'Hot Sauce'), ('none', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapeños'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapeños'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapeños'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
    ]
