# Generated by Django 5.2 on 2025-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_post_sauces_post_sauce_1_post_sauce_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='sandwich',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapenos'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapenos'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('onion', 'Onions'), ('cucumber', 'Cucumbers'), ('pickle', 'Pickles'), ('olive', 'Olives'), ('jalapeno', 'Jalapenos'), ('pepper', 'Green Peppers'), ('none', 'No Vegtables')], default='none', max_length=20),
        ),
    ]
