# Generated by Django 5.2 on 2025-04-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_rename_title_post_sandwich_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='about',
        ),
    ]
