# Generated by Django 5.2 on 2025-04-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rename_content_post_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
