# Generated by Django 5.2 on 2025-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_post_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vegan',
            field=models.CharField(choices=[('yes', 'Vegan'), ('no', 'Non Vegan')], default='no', max_length=20),
        ),
    ]
