# Generated by Django 5.2 on 2025-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_post_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bread',
            field=models.CharField(choices=[('White Bread', 'White Bread'), ('Brown Bread', 'Brown Bread')], default='white', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='meat',
            field=models.CharField(choices=[('Turkey', 'Turkey'), ('Chicken', 'Grilled Chicken'), ('Ham', 'Ham'), ('Roast Beef', 'Roast Beef'), ('Tuna', 'Tuna'), ('Salami', 'Salami'), ('None', 'No Meat')], default='chicken', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(choices=[('Under $5', 'Under $5'), ('$5 - $10', '$5 - $10'), ('$10 - $15', '$10 - $15'), ('Above $15', 'Above $15')], default='10-15', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('None', 'Hot Sauce'), ('None', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('None', 'Hot Sauce'), ('None', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('None', 'Hot Sauce'), ('None', 'No Sauce')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('6-inch', '6-inch'), ('Footlong', 'Footlong')], default='6', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='vegan',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Non Vegan', 'Non Vegan')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onions'), ('Cucumber', 'Cucumbers'), ('Pickle', 'Pickles'), ('Olive', 'Olives'), ('Jalapeno', 'Jalapenos'), ('Green Pepper', 'Green Peppers'), ('None', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onions'), ('Cucumber', 'Cucumbers'), ('Pickle', 'Pickles'), ('Olive', 'Olives'), ('Jalapeno', 'Jalapenos'), ('Green Pepper', 'Green Peppers'), ('None', 'No Vegtables')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onions'), ('Cucumber', 'Cucumbers'), ('Pickle', 'Pickles'), ('Olive', 'Olives'), ('Jalapeno', 'Jalapenos'), ('Green Pepper', 'Green Peppers'), ('None', 'No Vegtables')], default='none', max_length=20),
        ),
    ]
