# Generated by Django 5.2 on 2025-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_post_bread_alter_post_meat_alter_post_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bread',
            field=models.CharField(choices=[('White Bread', 'White Bread'), ('Brown Bread', 'Brown Bread')], default='White Bread', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='meat',
            field=models.CharField(choices=[('Turkey', 'Turkey'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Beef', 'Beef'), ('Tuna', 'Tuna'), ('Salami', 'Salami'), ('None', 'None')], default='Chicken', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(choices=[('Under $5', 'Under $5'), ('$5 - $10', '$5 - $10'), ('$10 - $15', '$10 - $15'), ('Above $15', 'Above $15')], default='$10 - $15', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('6-inch', '6-inch'), ('Footlong', 'Footlong')], default='6-inch', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='temp',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='Hot', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='vegan',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Non Vegan', 'Non Vegan')], default='Non Vegan', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onion'), ('Cucumber', 'Cucumber'), ('Pickle', 'Pickle'), ('Olive', 'Olivs'), ('Jalapeno', 'Jalapeno'), ('Green Pepper', 'Green Pepper'), ('None', 'No Vegtables')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onion'), ('Cucumber', 'Cucumber'), ('Pickle', 'Pickle'), ('Olive', 'Olivs'), ('Jalapeno', 'Jalapeno'), ('Green Pepper', 'Green Pepper'), ('None', 'No Vegtables')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Onion', 'Onion'), ('Cucumber', 'Cucumber'), ('Pickle', 'Pickle'), ('Olive', 'Olivs'), ('Jalapeno', 'Jalapeno'), ('Green Pepper', 'Green Pepper'), ('None', 'No Vegtables')], default='None', max_length=20),
        ),
    ]
