# Generated by Django 5.2 on 2025-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_post_bread_alter_post_meat_alter_post_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sandwich_image',
            field=models.ImageField(default='default_sandwich.jpg', upload_to='sandwich_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meat',
            field=models.CharField(choices=[('Turkey', 'Turkey'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Beef', 'Beef'), ('Tuna', 'Tuna'), ('Salami', 'Salami'), ('None', 'No Meat')], default='Chicken', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'No Sauce')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'No Sauce')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Ketchup', 'Ketchup'), ('BBQ Sauce', 'BBQ Sauce'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Honey Mustard', 'Honey Mustard'), ('Hot Sauce', 'Hot Sauce'), ('None', 'No Sauce')], default='None', max_length=20),
        ),
    ]
