# Generated by Django 5.2 on 2025-04-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
