# Generated by Django 5.2 on 2025-04-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_post_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='old_cart',
        ),
    ]
