# Generated by Django 5.2 on 2025-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_remove_post_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sandwich',
            field=models.CharField(max_length=20),
        ),
    ]
