# Generated by Django 5.2 on 2025-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_alter_post_bread_alter_post_meat_alter_post_sauce_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cheese',
            field=models.CharField(choices=[('American', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper Jack'), ('Provolone', 'Provolone'), ('Swiss', 'Swiss'), ('Mozzarella', 'Mozzarella'), ('Vegan Cheese', 'Vegan Cheese'), ('None', 'No Meat')], default='None', max_length=20),
        ),
    ]
