# Generated by Django 5.2 on 2025-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_post_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cheese',
            field=models.CharField(choices=[('American', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper Jack'), ('Provolone', 'Provolone'), ('Swiss', 'Swiss'), ('Mozzarella', 'Mozzarella'), ('Vegan Cheese', 'Vegan Cheese'), ('None', 'No Cheese')], default='None', max_length=20),
        ),
    ]
