# Generated by Django 5.2 on 2025-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_alter_post_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cheese',
            field=models.CharField(choices=[('None', 'No Cheese'), ('American', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper Jack'), ('Provolone', 'Provolone'), ('Swiss', 'Swiss'), ('Mozzarella', 'Mozzarella'), ('Vegan Cheese', 'Vegan Cheese')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='meat',
            field=models.CharField(choices=[('None', 'No Meat'), ('Grilled Chicken', 'Grilled Chicken'), ('Turkey', 'Turkey'), ('Ham', 'Ham'), ('Roast Beef', 'Roast Beef'), ('Tuna', 'Tuna'), ('Spicy Italian', 'Spicy Italian'), ('Bacon', 'Bacon'), ('Pepperoni', 'Pepperoni'), ('Salami', 'Salami')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo'), ('Oil', 'Oil'), ('Vinegar', 'Vinegar'), ('Salt', 'Salt'), ('Pepper', 'Pepper')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo'), ('Oil', 'Oil'), ('Vinegar', 'Vinegar'), ('Salt', 'Salt'), ('Pepper', 'Pepper')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo'), ('Oil', 'Oil'), ('Vinegar', 'Vinegar'), ('Salt', 'Salt'), ('Pepper', 'Pepper')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeño', 'Jalapeño'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeño', 'Jalapeño'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeño', 'Jalapeño'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
    ]
