# Generated by Django 5.2 on 2025-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_alter_post_cheese_alter_post_meat_alter_post_sauce_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sauce_1',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_2',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='sauce_3',
            field=models.CharField(choices=[('None', 'No Sauce'), ('Mayonnaise', 'Mayonnaise'), ('Mustard', 'Mustard'), ('Honey Mustard', 'Honey Mustard'), ('Chipotle Southwest', 'Chipotle Southwest'), ('Ranch', 'Ranch'), ('Sweet Onion', 'Sweet Onion'), ('BBQ Sauce', 'BBQ Sauce'), ('Buffalo', 'Buffalo')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_1',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeno', 'Jalapeno'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_2',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeno', 'Jalapeno'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='veggie_3',
            field=models.CharField(choices=[('None', 'No Vegtables'), ('Lettuce', 'Lettuce'), ('Spinach', 'Spinach'), ('Tomato', 'Tomato'), ('Cucumber', 'Cucumber'), ('Green Pepper', 'Green Pepper'), ('Onion', 'Onion'), ('Banana Pepper', 'Banana Pepper'), ('Jalapeno', 'Jalapeno'), ('Pickle', 'Pickle'), ('Olive', 'Olive')], default='None', max_length=20),
        ),
    ]
